language: node_js

node_js:
  - '6'

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - yarn prune

script:
  - yarn check

after_success:
  - yarn semantic-release

branches:
  on:
    branch: master
