language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm run build
  - npm run test-ssr
after_success:
  - npm run semantic-release
branches:
  on:
    branch: master
